import type React from "react";
import {
  SFAirplane,
  SFAirplaneCircleFill,
  SFAlarm,
  SFAlarmFill,
  SFAntennaRadiowavesLeftAndRight,
  SFAntennaRadiowavesLeftAndRightCircleFill,
  SFArchivebox,
  SFArchiveboxFill,
  SFArrowClockwise,
  SFArrowClockwiseCircleFill,
  SFArrowCounterclockwise,
  SFArrowCounterclockwiseCircleFill,
  SFArrowDown,
  SFArrowDownCircleFill,
  SFArrowLeft,
  SFArrowLeftCircleFill,
  SFArrowRight,
  SFArrowRightCircleFill,
  SFArrowUp,
  SFArrowUpCircleFill,
  SFAt,
  SFAtCircleFill,
  SFBag,
  SFBagFill,
  SFBedDouble,
  SFBedDoubleFill,
  SFBell,
  SFBellFill,
  SFBicycle,
  SFBicycleCircleFill,
  SFBolt,
  SFBoltFill,
  SFBook,
  SFBookFill,
  SFBookmark,
  SFBookmarkFill,
  SFBooksVertical,
  SFBooksVerticalFill,
  SFBriefcase,
  SFBriefcaseFill,
  SFBubble,
  SFBubbleFill,
  SFBubbleLeft,
  SFBubbleLeftFill,
  SFBuilding2,
  SFBuilding2Fill,
  SFBuildingColumns,
  SFBuildingColumnsFill,
  SFCalendar,
  SFCalendarCircleFill,
  SFCamera,
  SFCameraFill,
  SFCar,
  SFCarCircleFill,
  SFCart,
  SFCartFill,
  SFChartBar,
  SFChartBarFill,
  SFChartLineUptrendXyaxis,
  SFChartLineUptrendXyaxisCircleFill,
  SFChartPie,
  SFChartPieFill,
  SFCheckmark,
  SFCheckmarkCircleFill,
  SFCheckmarkSeal,
  SFCheckmarkSealFill,
  SFChevronDown,
  SFChevronDownCircleFill,
  SFChevronLeft,
  SFChevronLeftCircleFill,
  SFChevronRight,
  SFChevronRightCircleFill,
  SFChevronUp,
  SFChevronUpCircleFill,
  SFClipboard,
  SFClipboardFill,
  SFClock,
  SFClockFill,
  SFCloud,
  SFCloudFill,
  SFCpu,
  SFCpuFill,
  SFCreditcard,
  SFCreditcardFill,
  SFCross,
  SFCrossFill,
  SFCrown,
  SFCrownFill,
  SFCupAndSaucer,
  SFCupAndSaucerFill,
  SFDiamond,
  SFDiamondFill,
  SFDice,
  SFDiceFill,
  SFDocument,
  SFDocumentFill,
  SFDollarsign,
  SFDollarsignCircleFill,
  SFDrop,
  SFDropCircleFill,
  SFEllipsis,
  SFEllipsisCircleFill,
  SFEnvelope,
  SFEnvelopeFill,
  SFEurosign,
  SFEurosignCircleFill,
  SFExclamationmarkCircle,
  SFExclamationmarkCircleFill,
  SFEye,
  SFEyeFill,
  SFFaceDashed,
  SFFaceDashedFill,
  SFFacemask,
  SFFacemaskFill,
  SFFlag,
  SFFlagFill,
  SFFlame,
  SFFlameCircleFill,
  SFFolder,
  SFFolderFill,
  SFGamecontroller,
  SFGamecontrollerFill,
  SFGear,
  SFGearshapeFill,
  SFGift,
  SFGiftFill,
  SFGlobe,
  SFGlobeFill,
  SFHammer,
  SFHammerFill,
  SFHandRaised,
  SFHandRaisedFill,
  SFHandThumbsdown,
  SFHandThumbsdownFill,
  SFHandThumbsup,
  SFHandThumbsupFill,
  SFHandWave,
  SFHandWaveFill,
  SFHeadphones,
  SFHeadphonesCircleFill,
  SFHeart,
  SFHeartFill,
  SFHourglass,
  SFHourglassCircleFill,
  SFHouse,
  SFHouseFill,
  SFInfoCircle,
  SFInfoCircleFill,
  SFIphone,
  SFIphoneCircleFill,
  SFKey,
  SFKeyboard,
  SFKeyboardFill,
  SFKeyFill,
  SFLeaf,
  SFLeafCircleFill,
  SFLink,
  SFLinkCircleFill,
  SFListBullet,
  SFListBulletCircleFill,
  SFLocation,
  SFLocationFill,
  SFLock,
  SFLockFill,
  SFLockOpen,
  SFLockOpenFill,
  SFMagnifyingglass,
  SFMagnifyingglassCircleFill,
  SFMap,
  SFMapFill,
  SFMappin,
  SFMappinCircleFill,
  SFMessage,
  SFMessageFill,
  SFMetronome,
  SFMetronomeFill,
  SFMicrophone,
  SFMicrophoneFill,
  SFMinus,
  SFMinusCircleFill,
  SFMoon,
  SFMoonFill,
  SFNewspaper,
  SFNewspaperFill,
  SFPaintbrush,
  SFPaintbrushFill,
  SFPaintpalette,
  SFPaintpaletteFill,
  SFPaperclip,
  SFPaperclipCircleFill,
  SFPaperplane,
  SFPaperplaneFill,
  SFPause,
  SFPauseFill,
  SFPencil,
  SFPencilCircleFill,
  SFPerson,
  SFPerson2,
  SFPerson2Fill,
  SFPerson3,
  SFPerson3Fill,
  SFPersonCropCircle,
  SFPersonCropCircleFill,
  SFPersonFill,
  SFPhone,
  SFPhoneFill,
  SFPhoto,
  SFPhotoFill,
  SFPlay,
  SFPlayFill,
  SFPlus,
  SFPlusCircleFill,
  SFPower,
  SFPowerCircleFill,
  SFQuestionmarkCircle,
  SFQuestionmarkCircleFill,
  SFRepeat,
  SFRepeatCircleFill,
  SFScissors,
  SFScissorsCircleFill,
  SFShield,
  SFShieldFill,
  SFShuffle,
  SFShuffleCircleFill,
  SFSnowflake,
  SFSnowflakeCircleFill,
  SFSquareAndArrowDown,
  SFSquareAndArrowDownFill,
  SFSquareAndArrowUp,
  SFSquareAndArrowUpFill,
  SFStar,
  SFStarFill,
  SFStethoscope,
  SFStethoscopeCircleFill,
  SFSunMax,
  SFSunMaxFill,
  SFTag,
  SFTagFill,
  SFTimer,
  SFTimerCircleFill,
  SFTrash,
  SFTrashFill,
  SFTray,
  SFTrayFill,
  SFTrophy,
  SFTrophyFill,
  SFTv,
  SFTvFill,
  SFVideo,
  SFVideoFill,
  SFWaveform,
  SFWaveformCircleFill,
  SFWifi,
  SFWifiCircleFill,
  SFXmark,
  SFXmarkCircleFill,
  SFArrowUpArrowDown,
  SFArrowUpArrowDownCircleFill,
  SFArrowLeftArrowRight,
  SFArrowLeftArrowRightCircleFill,
  SFArrowUpAndDown,
  SFArrowUpAndDownCircleFill,
  SFBellBadge,
  SFBellBadgeFill,
  SFBellSlash,
  SFBellSlashFill,
  SFEnvelopeBadge,
  SFEnvelopeBadgeFill,
  SFEnvelopeOpen,
  SFEnvelopeOpenFill,
  SFSpeaker,
  SFSpeakerFill,
  SFSpeakerWave3,
  SFSpeakerWave3Fill,
  SFSpeakerSlash,
  SFSpeakerSlashFill,
  SFSpeakerCircle,
  SFSpeakerCircleFill,
  SFRecordCircle,
  SFRecordCircleFill,
  SFStopCircle,
  SFStopCircleFill,
  SFAirplayVideo,
  SFAirplayVideoCircleFill,
  SFAirplayAudio,
  SFAirplayAudioCircleFill,
  SFEyeSlash,
  SFEyeSlashFill,
  SFPin,
  SFPinFill,
  SFPinCircle,
  SFPinCircleFill,
  SFLocationCircle,
  SFLocationCircleFill,
  SFLocationSlash,
  SFLocationSlashFill,
  SFLightbulb,
  SFLightbulbFill,
  SFLightbulbCircle,
  SFLightbulbCircleFill,
  SFLightbulbMax,
  SFLightbulbMaxFill,
  SFFireplace,
  SFFireplaceFill,
  SFPrinter,
  SFPrinterFill,
  SFScanner,
  SFScannerFill,
  SFMacmini,
  SFMacminiFill,
  SFNumber,
  SFNumberCircleFill,
  SFTablecells,
  SFTablecellsFill,
  SFSquareGrid3x3,
  SFSquareGrid3x3Fill,
  SFSquareGrid2x2,
  SFSquareGrid2x2Fill,
  SFBasketball,
  SFBasketballFill,
  SFBaseball,
  SFBaseballFill,
  SFDumbbell,
  SFDumbbellFill,
  SFVolleyball,
  SFVolleyballFill,
  SFHockeyPuck,
  SFHockeyPuckFill,
  SFFigureRun,
  SFFigureRunCircleFill,
  SFFigureWalk,
  SFFigureWalkCircleFill,
  SFFigureYoga,
  SFFigureYogaCircleFill,
  SFFigureDance,
  SFFigureDanceCircleFill,
  SFFigureHiking,
  SFFigureHikingCircleFill,
  SFPersonBadgeKey,
  SFPersonBadgeKeyFill,
  SFTent,
  SFTentFill,
  SFBathtub,
  SFBathtubFill,
  SFSignpostRight,
  SFSignpostRightFill,
  SFTriangle,
  SFTriangleFill,
  SFHexagon,
  SFHexagonFill,
  SFStopwatch,
  SFStopwatchFill,
  // New icons
  SFAnt,
  SFAntFill,
  SFCat,
  SFCatFill,
  SFDog,
  SFDogFill,
  SFFish,
  SFFishFill,
  SFTortoise,
  SFTortoiseFill,
  SFHatCap,
  SFHatCapFill,
  SFHatWidebrim,
  SFHatWidebrimFill,
  SFShoe,
  SFShoeFill,
  SFTshirt,
  SFTshirtFill,
  SFMicrowave,
  SFMicrowaveFill,
  SFMug,
  SFMugFill,
  SFAmericanFootball,
  SFAmericanFootballFill,
  SFBackpack,
  SFBackpackFill,
  SFBinoculars,
  SFBinocularsFill,
  SFMedal,
  SFMedalFill,
  SFMedalStar,
  SFMedalStarFill,
  SFBeachUmbrella,
  SFBeachUmbrellaFill,
  SFSprinkler,
  SFSprinklerFill,
  SFTree,
  SFTreeFill,
  SFUmbrella,
  SFUmbrellaFill,
  SFFerry,
  SFFerryFill,
  SFAirplaneTicket,
  SFAirplaneTicketFill,
  SFSuitcaseRolling,
  SFSuitcaseRollingFill,
  SFSuitcase,
  SFSuitcaseFill,
  SFTram,
  SFTramFill,
  SFBalloon,
  SFBalloonFill,
  SFFilm,
  SFFilmFill,
  SFGuitars,
  SFGuitarsFill,
  SFPuzzlepiece,
  SFPuzzlepieceFill,
  SFTeddybear,
  SFTeddybearFill,
  SFAccessibility,
  SFAccessibilityFill,
  SFEar,
  SFEarFill,
  SFPill,
  SFPillFill,
  SFSyringe,
  SFSyringeFill,
  SFChair,
  SFChairFill,
  SFShippingbox,
  SFShippingboxFill,
  SFSofa,
  SFSofaFill,
  SFSwatchpalette,
  SFSwatchpaletteFill,
  SFWalletPass,
  SFWalletPassFill,
  SFBanknote,
  SFBanknoteFill,
  SFPills,
  SFPillsFill,
  SFTicket,
  SFTicketFill,
  SFEarbudsCase,
  SFEarbudsCaseFill,
  SFHeartCircle,
  SFHeartCircleFill,
  SFHouseLodge,
  SFHouseLodgeFill,
  SFComputermouse,
  SFComputermouseFill,
  SFFilmStack,
  SFFilmStackFill,
  SFSuitcaseCart,
  SFSuitcaseCartFill,
} from "sf-symbols-lib/monochrome";

type IconComponent = React.ComponentType<{
  className?: string;
  width?: number;
  height?: number;
}>;

export const BUTTON_ICON_MAP: Record<string, IconComponent> = {
  SFAirplane,                              SFAirplaneCircleFill,
  SFAlarm,                                 SFAlarmFill,
  SFAntennaRadiowavesLeftAndRight,         SFAntennaRadiowavesLeftAndRightCircleFill,
  SFArchivebox,                            SFArchiveboxFill,
  SFArrowClockwise,                        SFArrowClockwiseCircleFill,
  SFArrowCounterclockwise,                 SFArrowCounterclockwiseCircleFill,
  SFArrowDown,                             SFArrowDownCircleFill,
  SFArrowLeft,                             SFArrowLeftCircleFill,
  SFArrowRight,                            SFArrowRightCircleFill,
  SFArrowUp,                               SFArrowUpCircleFill,
  SFAt,                                    SFAtCircleFill,
  SFBag,                                   SFBagFill,
  SFBedDouble,                             SFBedDoubleFill,
  SFBell,                                  SFBellFill,
  SFBicycle,                               SFBicycleCircleFill,
  SFBolt,                                  SFBoltFill,
  SFBook,                                  SFBookFill,
  SFBookmark,                              SFBookmarkFill,
  SFBooksVertical,                         SFBooksVerticalFill,
  SFBriefcase,                             SFBriefcaseFill,
  SFBubble,                                SFBubbleFill,
  SFBubbleLeft,                            SFBubbleLeftFill,
  SFBuilding2,                             SFBuilding2Fill,
  SFBuildingColumns,                       SFBuildingColumnsFill,
  SFCalendar,                              SFCalendarCircleFill,
  SFCamera,                                SFCameraFill,
  SFCar,                                   SFCarCircleFill,
  SFCart,                                  SFCartFill,
  SFChartBar,                              SFChartBarFill,
  SFChartLineUptrendXyaxis,               SFChartLineUptrendXyaxisCircleFill,
  SFChartPie,                              SFChartPieFill,
  SFCheckmark,                             SFCheckmarkCircleFill,
  SFCheckmarkSeal,                         SFCheckmarkSealFill,
  SFChevronDown,                           SFChevronDownCircleFill,
  SFChevronLeft,                           SFChevronLeftCircleFill,
  SFChevronRight,                          SFChevronRightCircleFill,
  SFChevronUp,                             SFChevronUpCircleFill,
  SFClipboard,                             SFClipboardFill,
  SFClock,                                 SFClockFill,
  SFCloud,                                 SFCloudFill,
  SFCpu,                                   SFCpuFill,
  SFCreditcard,                            SFCreditcardFill,
  SFCross,                                 SFCrossFill,
  SFCrown,                                 SFCrownFill,
  SFCupAndSaucer,                          SFCupAndSaucerFill,
  SFDiamond,                               SFDiamondFill,
  SFDice,                                  SFDiceFill,
  SFDocument,                              SFDocumentFill,
  SFDollarsign,                            SFDollarsignCircleFill,
  SFDrop,                                  SFDropCircleFill,
  SFEllipsis,                              SFEllipsisCircleFill,
  SFEnvelope,                              SFEnvelopeFill,
  SFEurosign,                              SFEurosignCircleFill,
  SFExclamationmarkCircle,                 SFExclamationmarkCircleFill,
  SFEye,                                   SFEyeFill,
  SFFaceDashed,                            SFFaceDashedFill,
  SFFacemask,                              SFFacemaskFill,
  SFFlag,                                  SFFlagFill,
  SFFlame,                                 SFFlameCircleFill,
  SFFolder,                                SFFolderFill,
  SFGamecontroller,                        SFGamecontrollerFill,
  SFGear,                                  SFGearshapeFill,
  SFGift,                                  SFGiftFill,
  SFGlobe,                                 SFGlobeFill,
  SFHammer,                                SFHammerFill,
  SFHandRaised,                            SFHandRaisedFill,
  SFHandThumbsdown,                        SFHandThumbsdownFill,
  SFHandThumbsup,                          SFHandThumbsupFill,
  SFHandWave,                              SFHandWaveFill,
  SFHeadphones,                            SFHeadphonesCircleFill,
  SFHeart,                                 SFHeartFill,
  SFHourglass,                             SFHourglassCircleFill,
  SFHouse,                                 SFHouseFill,
  SFInfoCircle,                            SFInfoCircleFill,
  SFIphone,                                SFIphoneCircleFill,
  SFKey,                                   SFKeyFill,
  SFKeyboard,                              SFKeyboardFill,
  SFLeaf,                                  SFLeafCircleFill,
  SFLink,                                  SFLinkCircleFill,
  SFListBullet,                            SFListBulletCircleFill,
  SFLocation,                              SFLocationFill,
  SFLock,                                  SFLockFill,
  SFLockOpen,                              SFLockOpenFill,
  SFMagnifyingglass,                       SFMagnifyingglassCircleFill,
  SFMap,                                   SFMapFill,
  SFMappin,                                SFMappinCircleFill,
  SFMessage,                               SFMessageFill,
  SFMetronome,                             SFMetronomeFill,
  SFMicrophone,                            SFMicrophoneFill,
  SFMinus,                                 SFMinusCircleFill,
  SFMoon,                                  SFMoonFill,
  SFNewspaper,                             SFNewspaperFill,
  SFPaintbrush,                            SFPaintbrushFill,
  SFPaintpalette,                          SFPaintpaletteFill,
  SFPaperclip,                             SFPaperclipCircleFill,
  SFPaperplane,                            SFPaperplaneFill,
  SFPause,                                 SFPauseFill,
  SFPencil,                                SFPencilCircleFill,
  SFPerson,                                SFPersonFill,
  SFPerson2,                               SFPerson2Fill,
  SFPerson3,                               SFPerson3Fill,
  SFPersonCropCircle,                      SFPersonCropCircleFill,
  SFPhone,                                 SFPhoneFill,
  SFPhoto,                                 SFPhotoFill,
  SFPlay,                                  SFPlayFill,
  SFPlus,                                  SFPlusCircleFill,
  SFPower,                                 SFPowerCircleFill,
  SFQuestionmarkCircle,                    SFQuestionmarkCircleFill,
  SFRepeat,                                SFRepeatCircleFill,
  SFScissors,                              SFScissorsCircleFill,
  SFShield,                                SFShieldFill,
  SFShuffle,                               SFShuffleCircleFill,
  SFSnowflake,                             SFSnowflakeCircleFill,
  SFSquareAndArrowDown,                    SFSquareAndArrowDownFill,
  SFSquareAndArrowUp,                      SFSquareAndArrowUpFill,
  SFStar,                                  SFStarFill,
  SFStethoscope,                           SFStethoscopeCircleFill,
  SFSunMax,                                SFSunMaxFill,
  SFTag,                                   SFTagFill,
  SFTimer,                                 SFTimerCircleFill,
  SFTrash,                                 SFTrashFill,
  SFTray,                                  SFTrayFill,
  SFTrophy,                                SFTrophyFill,
  SFTv,                                    SFTvFill,
  SFVideo,                                 SFVideoFill,
  SFWaveform,                              SFWaveformCircleFill,
  SFWifi,                                  SFWifiCircleFill,
  SFXmark,                                 SFXmarkCircleFill,
  // Arrows (extra)
  SFArrowUpArrowDown,                      SFArrowUpArrowDownCircleFill,
  SFArrowLeftArrowRight,                   SFArrowLeftArrowRightCircleFill,
  SFArrowUpAndDown,                        SFArrowUpAndDownCircleFill,
  // Notifications (extra)
  SFBellBadge,                             SFBellBadgeFill,
  SFBellSlash,                             SFBellSlashFill,
  // Envelopes (extra)
  SFEnvelopeBadge,                         SFEnvelopeBadgeFill,
  SFEnvelopeOpen,                          SFEnvelopeOpenFill,
  // Audio & AV
  SFSpeaker,                               SFSpeakerFill,
  SFSpeakerWave3,                          SFSpeakerWave3Fill,
  SFSpeakerSlash,                          SFSpeakerSlashFill,
  SFSpeakerCircle,                         SFSpeakerCircleFill,
  SFRecordCircle,                          SFRecordCircleFill,
  SFStopCircle,                            SFStopCircleFill,
  SFAirplayVideo,                          SFAirplayVideoCircleFill,
  SFAirplayAudio,                          SFAirplayAudioCircleFill,
  // Vision (extra)
  SFEyeSlash,                              SFEyeSlashFill,
  // Location (extra)
  SFPin,                                   SFPinFill,
  SFPinCircle,                             SFPinCircleFill,
  SFLocationCircle,                        SFLocationCircleFill,
  SFLocationSlash,                         SFLocationSlashFill,
  // Illumination
  SFLightbulb,                             SFLightbulbFill,
  SFLightbulbCircle,                       SFLightbulbCircleFill,
  SFLightbulbMax,                          SFLightbulbMaxFill,
  // Devices & Appliances
  SFFireplace,                             SFFireplaceFill,
  SFPrinter,                               SFPrinterFill,
  SFScanner,                               SFScannerFill,
  SFMacmini,                               SFMacminiFill,
  // UI & Layout
  SFNumber,                                SFNumberCircleFill,
  SFTablecells,                            SFTablecellsFill,
  SFSquareGrid3x3,                         SFSquareGrid3x3Fill,
  SFSquareGrid2x2,                         SFSquareGrid2x2Fill,
  // Sports (extra)
  SFBasketball,                            SFBasketballFill,
  SFBaseball,                              SFBaseballFill,
  SFDumbbell,                              SFDumbbellFill,
  SFVolleyball,                            SFVolleyballFill,
  SFHockeyPuck,                            SFHockeyPuckFill,
  SFFigureRun,                             SFFigureRunCircleFill,
  SFFigureWalk,                            SFFigureWalkCircleFill,
  SFFigureYoga,                            SFFigureYogaCircleFill,
  SFFigureDance,                           SFFigureDanceCircleFill,
  SFFigureHiking,                          SFFigureHikingCircleFill,
  // People (extra)
  SFPersonBadgeKey,                        SFPersonBadgeKeyFill,
  // Outdoors (extra)
  SFTent,                                  SFTentFill,
  SFBathtub,                               SFBathtubFill,
  SFSignpostRight,                         SFSignpostRightFill,
  // Shapes
  SFTriangle,                              SFTriangleFill,
  SFHexagon,                               SFHexagonFill,
  // Time (extra)
  SFStopwatch,                             SFStopwatchFill,
  // Animals
  SFAnt,                                   SFAntFill,
  SFCat,                                   SFCatFill,
  SFDog,                                   SFDogFill,
  SFFish,                                  SFFishFill,
  SFTortoise,                              SFTortoiseFill,
  // Clothing & Fashion
  SFHatCap,                                SFHatCapFill,
  SFHatWidebrim,                           SFHatWidebrimFill,
  SFShoe,                                  SFShoeFill,
  SFTshirt,                                SFTshirtFill,
  // Food & Drink
  SFMicrowave,                             SFMicrowaveFill,
  SFMug,                                   SFMugFill,
  // Sports
  SFAmericanFootball,                      SFAmericanFootballFill,
  SFBackpack,                              SFBackpackFill,
  SFBinoculars,                            SFBinocularsFill,
  SFMedal,                                 SFMedalFill,
  SFMedalStar,                             SFMedalStarFill,
  // Nature
  SFBeachUmbrella,                         SFBeachUmbrellaFill,
  SFSprinkler,                             SFSprinklerFill,
  SFTree,                                  SFTreeFill,
  SFUmbrella,                              SFUmbrellaFill,
  // Travel & Transport
  SFFerry,                                 SFFerryFill,
  SFAirplaneTicket,                        SFAirplaneTicketFill,
  SFSuitcaseRolling,                       SFSuitcaseRollingFill,
  SFSuitcase,                              SFSuitcaseFill,
  SFTram,                                  SFTramFill,
  // Entertainment & Media
  SFBalloon,                               SFBalloonFill,
  SFFilm,                                  SFFilmFill,
  SFGuitars,                               SFGuitarsFill,
  SFPuzzlepiece,                           SFPuzzlepieceFill,
  SFTeddybear,                             SFTeddybearFill,
  // Health & Medical
  SFAccessibility,                         SFAccessibilityFill,
  SFEar,                                   SFEarFill,
  SFPill,                                  SFPillFill,
  SFSyringe,                               SFSyringeFill,
  // Home & Objects
  SFChair,                                 SFChairFill,
  SFShippingbox,                           SFShippingboxFill,
  SFSofa,                                  SFSofaFill,
  SFSwatchpalette,                         SFSwatchpaletteFill,
  SFWalletPass,                            SFWalletPassFill,
  // Commerce
  SFBanknote,                              SFBanknoteFill,
  SFPills,                                 SFPillsFill,
  SFTicket,                                SFTicketFill,
  // Technology & Devices
  SFEarbudsCase,                           SFEarbudsCaseFill,
  SFHeartCircle,                           SFHeartCircleFill,
  SFHouseLodge,                            SFHouseLodgeFill,
  SFComputermouse,                         SFComputermouseFill,
  // Misc
  SFFilmStack,                             SFFilmStackFill,
  SFSuitcaseCart,                          SFSuitcaseCartFill,
};
