// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFDiamond: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDiamond.js"),
  SFDiamondFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDiamondFill.js"),
  SFDice: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDice.js"),
  SFDiceFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDiceFill.js"),
  SFDocument: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDocument.js"),
  SFDocumentFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDocumentFill.js"),
  SFDog: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDog.js"),
  SFDogFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDogFill.js"),
  SFDollarsign: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDollarsign.js"),
  SFDollarsignCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDollarsignCircleFill.js"),
  SFDrop: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDrop.js"),
  SFDropCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDropCircleFill.js"),
  SFDumbbell: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDumbbell.js"),
  SFDumbbellFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFDumbbellFill.js"),
};
