// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFEar: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEar.js"),
  SFEarFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEarFill.js"),
  SFEarbudsCase: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEarbudsCase.js"),
  SFEarbudsCaseFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEarbudsCaseFill.js"),
  SFEllipsis: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEllipsis.js"),
  SFEllipsisCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEllipsisCircleFill.js"),
  SFEnvelope: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelope.js"),
  SFEnvelopeBadge: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelopeBadge.js"),
  SFEnvelopeBadgeFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelopeBadgeFill.js"),
  SFEnvelopeFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelopeFill.js"),
  SFEnvelopeOpen: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelopeOpen.js"),
  SFEnvelopeOpenFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEnvelopeOpenFill.js"),
  SFEurosign: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEurosign.js"),
  SFEurosignCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEurosignCircleFill.js"),
  SFExclamationmarkCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFExclamationmarkCircle.js"),
  SFExclamationmarkCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFExclamationmarkCircleFill.js"),
  SFEye: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEye.js"),
  SFEyeFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEyeFill.js"),
  SFEyeSlash: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEyeSlash.js"),
  SFEyeSlashFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFEyeSlashFill.js"),
};
