// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFGamecontroller: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGamecontroller.js"),
  SFGamecontrollerFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGamecontrollerFill.js"),
  SFGear: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGear.js"),
  SFGearshapeFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGearshapeFill.js"),
  SFGift: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGift.js"),
  SFGiftFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGiftFill.js"),
  SFGlobe: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGlobe.js"),
  SFGlobeFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGlobeFill.js"),
  SFGuitars: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGuitars.js"),
  SFGuitarsFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFGuitarsFill.js"),
};
