// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFInfoCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFInfoCircle.js"),
  SFInfoCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFInfoCircleFill.js"),
  SFIphone: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFIphone.js"),
  SFIphoneCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFIphoneCircleFill.js"),
};
