// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFKey: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFKey.js"),
  SFKeyFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFKeyFill.js"),
  SFKeyboard: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFKeyboard.js"),
  SFKeyboardFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFKeyboardFill.js"),
};
