// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFLeaf: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLeaf.js"),
  SFLeafCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLeafCircleFill.js"),
  SFLightbulb: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulb.js"),
  SFLightbulbCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulbCircle.js"),
  SFLightbulbCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulbCircleFill.js"),
  SFLightbulbFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulbFill.js"),
  SFLightbulbMax: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulbMax.js"),
  SFLightbulbMaxFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLightbulbMaxFill.js"),
  SFLink: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLink.js"),
  SFLinkCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLinkCircleFill.js"),
  SFListBullet: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFListBullet.js"),
  SFListBulletCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFListBulletCircleFill.js"),
  SFLocation: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocation.js"),
  SFLocationCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocationCircle.js"),
  SFLocationCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocationCircleFill.js"),
  SFLocationFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocationFill.js"),
  SFLocationSlash: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocationSlash.js"),
  SFLocationSlashFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLocationSlashFill.js"),
  SFLock: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLock.js"),
  SFLockFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLockFill.js"),
  SFLockOpen: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLockOpen.js"),
  SFLockOpenFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFLockOpenFill.js"),
};
