// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFNewspaper: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFNewspaper.js"),
  SFNewspaperFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFNewspaperFill.js"),
  SFNumber: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFNumber.js"),
  SFNumberCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFNumberCircleFill.js"),
};
