// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFQuestionmarkCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFQuestionmarkCircle.js"),
  SFQuestionmarkCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFQuestionmarkCircleFill.js"),
};
