// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFRecordCircle: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFRecordCircle.js"),
  SFRecordCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFRecordCircleFill.js"),
  SFRepeat: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFRepeat.js"),
  SFRepeatCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFRepeatCircleFill.js"),
};
