// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFUmbrella: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFUmbrella.js"),
  SFUmbrellaFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFUmbrellaFill.js"),
};
