// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFVideo: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFVideo.js"),
  SFVideoFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFVideoFill.js"),
  SFVolleyball: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFVolleyball.js"),
  SFVolleyballFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFVolleyballFill.js"),
};
