// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFWalletPass: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWalletPass.js"),
  SFWalletPassFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWalletPassFill.js"),
  SFWaveform: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWaveform.js"),
  SFWaveformCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWaveformCircleFill.js"),
  SFWifi: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWifi.js"),
  SFWifiCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFWifiCircleFill.js"),
};
