// Generated by scripts/generate-frontend-button-icon-buckets.mjs. Do not edit manually.
import type { MonochromeIconLoader } from "@/lib/buttonIconLoaders.ts";

export const monochromeIconLoaders: Record<string, MonochromeIconLoader> = {
  SFXmark: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFXmark.js"),
  SFXmarkCircleFill: () => import("../../../../../node_modules/sf-symbols-lib/dist/monochrome/icons/SFXmarkCircleFill.js"),
};
