import type { ComponentType } from "react";

import type { IconProps } from "@phosphor-icons/react";
import {
  AirplaneIcon,
  ArchiveBoxIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BankIcon,
  BellIcon,
  BookmarkIcon,
  BookIcon,
  BooksIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CarIcon,
  ChartBarIcon,
  ChartLineUpIcon,
  ChartPieSliceIcon,
  ChatCircleIcon,
  ChatCircleTextIcon,
  ClipboardTextIcon,
  CreditCardIcon,
  CurrencyCircleDollarIcon,
  DiceFiveIcon,
  EnvelopeIcon,
  EyeIcon,
  FileIcon,
  FolderIcon,
  GameControllerIcon,
  GearIcon,
  GiftIcon,
  GlobeIcon,
  HandPalmIcon,
  HandWavingIcon,
  HeadphonesIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  KeyIcon,
  ListBulletsIcon,
  LockIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MapTrifoldIcon,
  MicrophoneIcon,
  MusicNotesIcon,
  NewspaperIcon,
  PaperclipIcon,
  PaperPlaneTiltIcon,
  PauseIcon,
  PencilSimpleIcon,
  PhoneIcon,
  PlayIcon,
  ReceiptIcon,
  RepeatIcon,
  RssIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  ShuffleIcon,
  SmileyIcon,
  TagIcon,
  TelevisionIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrayIcon,
  UserCircleIcon,
  UserIcon,
  UsersThreeIcon,
  VideoCameraIcon,
  WaveformIcon,
} from "@phosphor-icons/react";

export type ButtonIconComponent = ComponentType<IconProps>;

function withDuotone(Icon: ButtonIconComponent): ButtonIconComponent {
  function DuotoneButtonIcon(props: IconProps) {
    return <Icon weight="duotone" {...props} />;
  }

  DuotoneButtonIcon.displayName = `Duotone${Icon.displayName ?? Icon.name ?? "ButtonIcon"}`;
  return DuotoneButtonIcon;
}

export const BUTTON_ICON_COMPONENTS = {
  "arrow-down": withDuotone(ArrowDownIcon),
  "arrow-left": withDuotone(ArrowLeftIcon),
  "arrow-right": withDuotone(ArrowRightIcon),
  "arrow-up": withDuotone(ArrowUpIcon),
  "arrow-clockwise": withDuotone(ArrowClockwiseIcon),
  "arrow-counter-clockwise": withDuotone(ArrowCounterClockwiseIcon),
  "caret-down": withDuotone(CaretDownIcon),
  "caret-up": withDuotone(CaretUpIcon),
  "caret-left": withDuotone(CaretLeftIcon),
  "caret-right": withDuotone(CaretRightIcon),
  bell: withDuotone(BellIcon),
  "chat-circle": withDuotone(ChatCircleIcon),
  "chat-circle-text": withDuotone(ChatCircleTextIcon),
  envelope: withDuotone(EnvelopeIcon),
  phone: withDuotone(PhoneIcon),
  microphone: withDuotone(MicrophoneIcon),
  "paper-plane-tilt": withDuotone(PaperPlaneTiltIcon),
  "video-camera": withDuotone(VideoCameraIcon),
  waveform: withDuotone(WaveformIcon),
  rss: withDuotone(RssIcon),
  user: withDuotone(UserIcon),
  "users-three": withDuotone(UsersThreeIcon),
  "user-circle": withDuotone(UserCircleIcon),
  "thumbs-up": withDuotone(ThumbsUpIcon),
  "thumbs-down": withDuotone(ThumbsDownIcon),
  "hand-palm": withDuotone(HandPalmIcon),
  "hand-waving": withDuotone(HandWavingIcon),
  smiley: withDuotone(SmileyIcon),
  play: withDuotone(PlayIcon),
  pause: withDuotone(PauseIcon),
  repeat: withDuotone(RepeatIcon),
  shuffle: withDuotone(ShuffleIcon),
  camera: withDuotone(CameraIcon),
  image: withDuotone(ImageIcon),
  television: withDuotone(TelevisionIcon),
  headphones: withDuotone(HeadphonesIcon),
  "game-controller": withDuotone(GameControllerIcon),
  "music-notes": withDuotone(MusicNotesIcon),
  "dice-five": withDuotone(DiceFiveIcon),
  "archive-box": withDuotone(ArchiveBoxIcon),
  book: withDuotone(BookIcon),
  books: withDuotone(BooksIcon),
  "clipboard-text": withDuotone(ClipboardTextIcon),
  file: withDuotone(FileIcon),
  folder: withDuotone(FolderIcon),
  newspaper: withDuotone(NewspaperIcon),
  paperclip: withDuotone(PaperclipIcon),
  tray: withDuotone(TrayIcon),
  bookmark: withDuotone(BookmarkIcon),
  "shopping-bag": withDuotone(ShoppingBagIcon),
  "shopping-cart": withDuotone(ShoppingCartIcon),
  "credit-card": withDuotone(CreditCardIcon),
  "currency-circle-dollar": withDuotone(CurrencyCircleDollarIcon),
  gift: withDuotone(GiftIcon),
  tag: withDuotone(TagIcon),
  receipt: withDuotone(ReceiptIcon),
  bank: withDuotone(BankIcon),
  globe: withDuotone(GlobeIcon),
  house: withDuotone(HouseIcon),
  "map-trifold": withDuotone(MapTrifoldIcon),
  "map-pin": withDuotone(MapPinIcon),
  airplane: withDuotone(AirplaneIcon),
  car: withDuotone(CarIcon),
  key: withDuotone(KeyIcon),
  lock: withDuotone(LockIcon),
  "shield-check": withDuotone(ShieldCheckIcon),
  gear: withDuotone(GearIcon),
  "chart-bar": withDuotone(ChartBarIcon),
  "chart-line-up": withDuotone(ChartLineUpIcon),
  "chart-pie-slice": withDuotone(ChartPieSliceIcon),
  "list-bullets": withDuotone(ListBulletsIcon),
  "magnifying-glass": withDuotone(MagnifyingGlassIcon),
  "pencil-simple": withDuotone(PencilSimpleIcon),
  eye: withDuotone(EyeIcon),
  heart: withDuotone(HeartIcon),
} as const satisfies Record<string, ButtonIconComponent>;

export type ButtonIconName = keyof typeof BUTTON_ICON_COMPONENTS;

export interface ButtonIconEntry {
  name: ButtonIconName;
  label: string;
  keywords?: readonly string[];
}

export const BUTTON_ICON_LIST: readonly ButtonIconEntry[] = [
  { name: "arrow-down", label: "Arrow Down", keywords: ["down"] },
  { name: "arrow-left", label: "Arrow Left", keywords: ["left"] },
  { name: "arrow-right", label: "Arrow Right", keywords: ["right"] },
  { name: "arrow-up", label: "Arrow Up", keywords: ["up"] },
  { name: "arrow-clockwise", label: "Arrow Clockwise", keywords: ["refresh", "reload"] },
  {
    name: "arrow-counter-clockwise",
    label: "Arrow Counter Clockwise",
    keywords: ["undo", "back"],
  },
  { name: "caret-down", label: "Caret Down", keywords: ["chevron", "down"] },
  { name: "caret-up", label: "Caret Up", keywords: ["chevron", "up"] },
  { name: "caret-left", label: "Caret Left", keywords: ["chevron", "left"] },
  { name: "caret-right", label: "Caret Right", keywords: ["chevron", "right"] },
  { name: "bell", label: "Bell", keywords: ["notification", "alert"] },
  { name: "chat-circle", label: "Chat Circle", keywords: ["message", "bubble"] },
  { name: "chat-circle-text", label: "Chat Circle Text", keywords: ["message", "text"] },
  { name: "envelope", label: "Envelope", keywords: ["mail", "email"] },
  { name: "phone", label: "Phone", keywords: ["call", "telephone"] },
  { name: "microphone", label: "Microphone", keywords: ["audio", "voice"] },
  { name: "paper-plane-tilt", label: "Paper Plane", keywords: ["send"] },
  { name: "video-camera", label: "Video Camera", keywords: ["video"] },
  { name: "waveform", label: "Waveform", keywords: ["audio", "sound"] },
  { name: "user", label: "User", keywords: ["person"] },
  { name: "users-three", label: "Users", keywords: ["group", "people"] },
  { name: "user-circle", label: "User Circle", keywords: ["profile", "account"] },
  { name: "thumbs-up", label: "Thumbs Up", keywords: ["like"] },
  { name: "thumbs-down", label: "Thumbs Down", keywords: ["dislike"] },
  { name: "hand-palm", label: "Hand Palm", keywords: ["stop", "halt"] },
  { name: "hand-waving", label: "Hand Waving", keywords: ["hello"] },
  { name: "smiley", label: "Smiley", keywords: ["face", "happy"] },
  { name: "play", label: "Play", keywords: ["start"] },
  { name: "pause", label: "Pause", keywords: ["stop"] },
  { name: "repeat", label: "Repeat", keywords: ["loop"] },
  { name: "shuffle", label: "Shuffle", keywords: ["random"] },
  { name: "camera", label: "Camera", keywords: ["photo"] },
  { name: "image", label: "Image", keywords: ["picture", "photo"] },
  { name: "television", label: "Television", keywords: ["tv", "screen"] },
  { name: "headphones", label: "Headphones", keywords: ["audio", "music"] },
  { name: "game-controller", label: "Game Controller", keywords: ["gaming"] },
  { name: "music-notes", label: "Music Notes", keywords: ["music", "audio"] },
  { name: "dice-five", label: "Dice", keywords: ["game", "random"] },
  { name: "archive-box", label: "Archive Box", keywords: ["archive", "storage"] },
  { name: "book", label: "Book", keywords: ["read"] },
  { name: "books", label: "Books", keywords: ["library", "read"] },
  { name: "clipboard-text", label: "Clipboard Text", keywords: ["notes", "copy"] },
  { name: "file", label: "File", keywords: ["document"] },
  { name: "folder", label: "Folder", keywords: ["directory"] },
  { name: "newspaper", label: "Newspaper", keywords: ["news", "article"] },
  { name: "paperclip", label: "Paperclip", keywords: ["attachment"] },
  { name: "bookmark", label: "Bookmark", keywords: ["save"] },
  { name: "shopping-bag", label: "Shopping Bag", keywords: ["bag", "shop"] },
  { name: "shopping-cart", label: "Shopping Cart", keywords: ["cart", "shop"] },
  { name: "credit-card", label: "Credit Card", keywords: ["payment"] },
  {
    name: "currency-circle-dollar",
    label: "Currency Circle Dollar",
    keywords: ["money", "price"],
  },
  { name: "gift", label: "Gift", keywords: ["present"] },
  { name: "tag", label: "Tag", keywords: ["label", "price"] },
  { name: "receipt", label: "Receipt", keywords: ["invoice", "bill"] },
  { name: "globe", label: "Globe", keywords: ["world", "website"] },
  { name: "house", label: "House", keywords: ["home"] },
  { name: "map-trifold", label: "Map Trifold", keywords: ["map", "location"] },
  { name: "map-pin", label: "Map Pin", keywords: ["location", "pin"] },
  { name: "airplane", label: "Airplane", keywords: ["flight", "travel"] },
  { name: "car", label: "Car", keywords: ["vehicle", "travel"] },
  { name: "key", label: "Key", keywords: ["access"] },
  { name: "lock", label: "Lock", keywords: ["secure", "privacy"] },
  { name: "shield-check", label: "Shield Check", keywords: ["security", "safe"] },
  { name: "gear", label: "Gear", keywords: ["settings"] },
  { name: "chart-bar", label: "Chart Bar", keywords: ["analytics", "stats"] },
  { name: "chart-line-up", label: "Chart Line Up", keywords: ["analytics", "growth"] },
  { name: "chart-pie-slice", label: "Chart Pie Slice", keywords: ["analytics", "stats"] },
  { name: "list-bullets", label: "List Bullets", keywords: ["menu", "list"] },
  { name: "magnifying-glass", label: "Magnifying Glass", keywords: ["search"] },
  { name: "pencil-simple", label: "Pencil Simple", keywords: ["edit", "write"] },
  { name: "eye", label: "Eye", keywords: ["view", "show"] },
  { name: "heart", label: "Heart", keywords: ["favorite", "like"] },
];

export function getButtonIconComponent(name: string | null | undefined): ButtonIconComponent | null {
  if (!name || !(name in BUTTON_ICON_COMPONENTS)) {
    return null;
  }

  return BUTTON_ICON_COMPONENTS[name as ButtonIconName];
}
