import type React from "react";
import {
  SFAirplane,
  SFAirplaneCircleFill,
  SFAlarm,
  SFAlarmFill,
  SFAntennaRadiowavesLeftAndRight,
  SFAntennaRadiowavesLeftAndRightCircleFill,
  SFArchivebox,
  SFArchiveboxFill,
  SFArrowClockwise,
  SFArrowClockwiseCircleFill,
  SFArrowCounterclockwise,
  SFArrowCounterclockwiseCircleFill,
  SFArrowDown,
  SFArrowDownCircleFill,
  SFArrowLeft,
  SFArrowLeftCircleFill,
  SFArrowRight,
  SFArrowRightCircleFill,
  SFArrowUp,
  SFArrowUpCircleFill,
  SFAt,
  SFAtCircleFill,
  SFBag,
  SFBagFill,
  SFBedDouble,
  SFBedDoubleFill,
  SFBell,
  SFBellFill,
  SFBicycle,
  SFBicycleCircleFill,
  SFBolt,
  SFBoltFill,
  SFBook,
  SFBookFill,
  SFBookmark,
  SFBookmarkFill,
  SFBooksVertical,
  SFBooksVerticalFill,
  SFBriefcase,
  SFBriefcaseFill,
  SFBubble,
  SFBubbleFill,
  SFBubbleLeft,
  SFBubbleLeftFill,
  SFBuilding2,
  SFBuilding2Fill,
  SFBuildingColumns,
  SFBuildingColumnsFill,
  SFCalendar,
  SFCalendarCircleFill,
  SFCamera,
  SFCameraFill,
  SFCar,
  SFCarCircleFill,
  SFCart,
  SFCartFill,
  SFChartBar,
  SFChartBarFill,
  SFChartLineUptrendXyaxis,
  SFChartLineUptrendXyaxisCircleFill,
  SFChartPie,
  SFChartPieFill,
  SFCheckmark,
  SFCheckmarkCircleFill,
  SFCheckmarkSeal,
  SFCheckmarkSealFill,
  SFChevronDown,
  SFChevronDownCircleFill,
  SFChevronLeft,
  SFChevronLeftCircleFill,
  SFChevronRight,
  SFChevronRightCircleFill,
  SFChevronUp,
  SFChevronUpCircleFill,
  SFClipboard,
  SFClipboardFill,
  SFClock,
  SFClockFill,
  SFCloud,
  SFCloudFill,
  SFCpu,
  SFCpuFill,
  SFCreditcard,
  SFCreditcardFill,
  SFCross,
  SFCrossFill,
  SFCrown,
  SFCrownFill,
  SFCupAndSaucer,
  SFCupAndSaucerFill,
  SFDiamond,
  SFDiamondFill,
  SFDice,
  SFDiceFill,
  SFDocument,
  SFDocumentFill,
  SFDollarsign,
  SFDollarsignCircleFill,
  SFDrop,
  SFDropCircleFill,
  SFEllipsis,
  SFEllipsisCircleFill,
  SFEnvelope,
  SFEnvelopeFill,
  SFEurosign,
  SFEurosignCircleFill,
  SFExclamationmarkCircle,
  SFExclamationmarkCircleFill,
  SFEye,
  SFEyeFill,
  SFFaceDashed,
  SFFaceDashedFill,
  SFFacemask,
  SFFacemaskFill,
  SFFlag,
  SFFlagFill,
  SFFlame,
  SFFlameCircleFill,
  SFFolder,
  SFFolderFill,
  SFGamecontroller,
  SFGamecontrollerFill,
  SFGear,
  SFGearshapeFill,
  SFGift,
  SFGiftFill,
  SFGlobe,
  SFGlobeFill,
  SFHammer,
  SFHammerFill,
  SFHandRaised,
  SFHandRaisedFill,
  SFHandThumbsdown,
  SFHandThumbsdownFill,
  SFHandThumbsup,
  SFHandThumbsupFill,
  SFHandWave,
  SFHandWaveFill,
  SFHeadphones,
  SFHeadphonesCircleFill,
  SFHeart,
  SFHeartFill,
  SFHourglass,
  SFHourglassCircleFill,
  SFHouse,
  SFHouseFill,
  SFInfoCircle,
  SFInfoCircleFill,
  SFIphone,
  SFIphoneCircleFill,
  SFKey,
  SFKeyboard,
  SFKeyboardFill,
  SFKeyFill,
  SFLeaf,
  SFLeafCircleFill,
  SFLink,
  SFLinkCircleFill,
  SFListBullet,
  SFListBulletCircleFill,
  SFLocation,
  SFLocationFill,
  SFLock,
  SFLockFill,
  SFLockOpen,
  SFLockOpenFill,
  SFMagnifyingglass,
  SFMagnifyingglassCircleFill,
  SFMap,
  SFMapFill,
  SFMappin,
  SFMappinCircleFill,
  SFMessage,
  SFMessageFill,
  SFMetronome,
  SFMetronomeFill,
  SFMicrophone,
  SFMicrophoneFill,
  SFMinus,
  SFMinusCircleFill,
  SFMoon,
  SFMoonFill,
  SFNewspaper,
  SFNewspaperFill,
  SFPaintbrush,
  SFPaintbrushFill,
  SFPaintpalette,
  SFPaintpaletteFill,
  SFPaperclip,
  SFPaperclipCircleFill,
  SFPaperplane,
  SFPaperplaneFill,
  SFPause,
  SFPauseFill,
  SFPencil,
  SFPencilCircleFill,
  SFPerson,
  SFPerson2,
  SFPerson2Fill,
  SFPerson3,
  SFPerson3Fill,
  SFPersonCropCircle,
  SFPersonCropCircleFill,
  SFPersonFill,
  SFPhone,
  SFPhoneFill,
  SFPhoto,
  SFPhotoFill,
  SFPlay,
  SFPlayFill,
  SFPlus,
  SFPlusCircleFill,
  SFPower,
  SFPowerCircleFill,
  SFQuestionmarkCircle,
  SFQuestionmarkCircleFill,
  SFRepeat,
  SFRepeatCircleFill,
  SFScissors,
  SFScissorsCircleFill,
  SFShield,
  SFShieldFill,
  SFShuffle,
  SFShuffleCircleFill,
  SFSnowflake,
  SFSnowflakeCircleFill,
  SFSquareAndArrowDown,
  SFSquareAndArrowDownFill,
  SFSquareAndArrowUp,
  SFSquareAndArrowUpFill,
  SFStar,
  SFStarFill,
  SFStethoscope,
  SFStethoscopeCircleFill,
  SFSunMax,
  SFSunMaxFill,
  SFTag,
  SFTagFill,
  SFTimer,
  SFTimerCircleFill,
  SFTrash,
  SFTrashFill,
  SFTray,
  SFTrayFill,
  SFTrophy,
  SFTrophyFill,
  SFTv,
  SFTvFill,
  SFVideo,
  SFVideoFill,
  SFWaveform,
  SFWaveformCircleFill,
  SFWifi,
  SFWifiCircleFill,
  SFXmark,
  SFXmarkCircleFill,
  // New icons
  SFArrowUpArrowDown,
  SFArrowUpArrowDownCircleFill,
  SFArrowLeftArrowRight,
  SFArrowLeftArrowRightCircleFill,
  SFArrowUpAndDown,
  SFArrowUpAndDownCircleFill,
  SFBellBadge,
  SFBellBadgeFill,
  SFBellSlash,
  SFBellSlashFill,
  SFEnvelopeBadge,
  SFEnvelopeBadgeFill,
  SFEnvelopeOpen,
  SFEnvelopeOpenFill,
  SFSpeaker,
  SFSpeakerFill,
  SFSpeakerWave3,
  SFSpeakerWave3Fill,
  SFSpeakerSlash,
  SFSpeakerSlashFill,
  SFSpeakerCircle,
  SFSpeakerCircleFill,
  SFRecordCircle,
  SFRecordCircleFill,
  SFStopCircle,
  SFStopCircleFill,
  SFAirplayVideo,
  SFAirplayVideoCircleFill,
  SFAirplayAudio,
  SFAirplayAudioCircleFill,
  SFEyeSlash,
  SFEyeSlashFill,
  SFPin,
  SFPinFill,
  SFPinCircle,
  SFPinCircleFill,
  SFLocationCircle,
  SFLocationCircleFill,
  SFLocationSlash,
  SFLocationSlashFill,
  SFLightbulb,
  SFLightbulbFill,
  SFLightbulbCircle,
  SFLightbulbCircleFill,
  SFLightbulbMax,
  SFLightbulbMaxFill,
  SFFireplace,
  SFFireplaceFill,
  SFPrinter,
  SFPrinterFill,
  SFScanner,
  SFScannerFill,
  SFNumber,
  SFNumberCircleFill,
  SFTablecells,
  SFTablecellsFill,
  SFSquareGrid3x3,
  SFSquareGrid3x3Fill,
  SFSquareGrid2x2,
  SFSquareGrid2x2Fill,
  SFMacmini,
  SFMacminiFill,
  SFBasketball,
  SFBasketballFill,
  SFBaseball,
  SFBaseballFill,
  SFDumbbell,
  SFDumbbellFill,
  SFVolleyball,
  SFVolleyballFill,
  SFHockeyPuck,
  SFHockeyPuckFill,
  SFFigureRun,
  SFFigureRunCircleFill,
  SFFigureWalk,
  SFFigureWalkCircleFill,
  SFFigureYoga,
  SFFigureYogaCircleFill,
  SFFigureDance,
  SFFigureDanceCircleFill,
  SFFigureHiking,
  SFFigureHikingCircleFill,
  SFPersonBadgeKey,
  SFPersonBadgeKeyFill,
  SFTent,
  SFTentFill,
  SFBathtub,
  SFBathtubFill,
  SFSignpostRight,
  SFSignpostRightFill,
  SFTriangle,
  SFTriangleFill,
  SFHexagon,
  SFHexagonFill,
  SFStopwatch,
  SFStopwatchFill,
  // New icons
  SFAnt,
  SFAntFill,
  SFCat,
  SFCatFill,
  SFDog,
  SFDogFill,
  SFFish,
  SFFishFill,
  SFTortoise,
  SFTortoiseFill,
  SFHatCap,
  SFHatCapFill,
  SFHatWidebrim,
  SFHatWidebrimFill,
  SFShoe,
  SFShoeFill,
  SFTshirt,
  SFTshirtFill,
  SFMicrowave,
  SFMicrowaveFill,
  SFMug,
  SFMugFill,
  SFAmericanFootball,
  SFAmericanFootballFill,
  SFBackpack,
  SFBackpackFill,
  SFBinoculars,
  SFBinocularsFill,
  SFMedal,
  SFMedalFill,
  SFMedalStar,
  SFMedalStarFill,
  SFBeachUmbrella,
  SFBeachUmbrellaFill,
  SFSprinkler,
  SFSprinklerFill,
  SFTree,
  SFTreeFill,
  SFUmbrella,
  SFUmbrellaFill,
  SFFerry,
  SFFerryFill,
  SFAirplaneTicket,
  SFAirplaneTicketFill,
  SFSuitcaseRolling,
  SFSuitcaseRollingFill,
  SFSuitcase,
  SFSuitcaseFill,
  SFTram,
  SFTramFill,
  SFBalloon,
  SFBalloonFill,
  SFFilm,
  SFFilmFill,
  SFGuitars,
  SFGuitarsFill,
  SFPuzzlepiece,
  SFPuzzlepieceFill,
  SFTeddybear,
  SFTeddybearFill,
  SFAccessibility,
  SFAccessibilityFill,
  SFEar,
  SFEarFill,
  SFPill,
  SFPillFill,
  SFSyringe,
  SFSyringeFill,
  SFChair,
  SFChairFill,
  SFShippingbox,
  SFShippingboxFill,
  SFSofa,
  SFSofaFill,
  SFSwatchpalette,
  SFSwatchpaletteFill,
  SFWalletPass,
  SFWalletPassFill,
  SFBanknote,
  SFBanknoteFill,
  SFPills,
  SFPillsFill,
  SFTicket,
  SFTicketFill,
  SFEarbudsCase,
  SFEarbudsCaseFill,
  SFHeartCircle,
  SFHeartCircleFill,
  SFHouseLodge,
  SFHouseLodgeFill,
  SFComputermouse,
  SFComputermouseFill,
  SFFilmStack,
  SFFilmStackFill,
  SFSuitcaseCart,
  SFSuitcaseCartFill,
} from "sf-symbols-lib/monochrome";

export type IconComponent = React.ComponentType<{
  className?: string;
  width?: number;
  height?: number;
}>;

export interface ButtonIconEntry {
  label: string;
  outlineName: string;
  filledName: string;
  Outline: IconComponent;
  Filled: IconComponent;
}

export const BUTTON_ICON_LIST: ButtonIconEntry[] = [
  // Arrows & Navigation
  { label: "Arrow Down",           outlineName: "SFArrowDown",                              filledName: "SFArrowDownCircleFill",                       Outline: SFArrowDown,                              Filled: SFArrowDownCircleFill },
  { label: "Arrow Left",           outlineName: "SFArrowLeft",                              filledName: "SFArrowLeftCircleFill",                       Outline: SFArrowLeft,                              Filled: SFArrowLeftCircleFill },
  { label: "Arrow Right",          outlineName: "SFArrowRight",                             filledName: "SFArrowRightCircleFill",                      Outline: SFArrowRight,                             Filled: SFArrowRightCircleFill },
  { label: "Arrow Up",             outlineName: "SFArrowUp",                                filledName: "SFArrowUpCircleFill",                         Outline: SFArrowUp,                                Filled: SFArrowUpCircleFill },
  { label: "Arrow Clockwise",      outlineName: "SFArrowClockwise",                         filledName: "SFArrowClockwiseCircleFill",                  Outline: SFArrowClockwise,                         Filled: SFArrowClockwiseCircleFill },
  { label: "Arrow Counterclockwise", outlineName: "SFArrowCounterclockwise",                filledName: "SFArrowCounterclockwiseCircleFill",           Outline: SFArrowCounterclockwise,                  Filled: SFArrowCounterclockwiseCircleFill },
  { label: "Chevron Down",         outlineName: "SFChevronDown",                            filledName: "SFChevronDownCircleFill",                     Outline: SFChevronDown,                            Filled: SFChevronDownCircleFill },
  { label: "Chevron Up",           outlineName: "SFChevronUp",                              filledName: "SFChevronUpCircleFill",                       Outline: SFChevronUp,                              Filled: SFChevronUpCircleFill },
  { label: "Chevron Left",         outlineName: "SFChevronLeft",                            filledName: "SFChevronLeftCircleFill",                     Outline: SFChevronLeft,                            Filled: SFChevronLeftCircleFill },
  { label: "Chevron Right",        outlineName: "SFChevronRight",                           filledName: "SFChevronRightCircleFill",                    Outline: SFChevronRight,                           Filled: SFChevronRightCircleFill },
  // Communication
  { label: "Bell",                 outlineName: "SFBell",                                   filledName: "SFBellFill",                                  Outline: SFBell,                                   Filled: SFBellFill },
  { label: "Bubble",               outlineName: "SFBubble",                                 filledName: "SFBubbleFill",                                Outline: SFBubble,                                 Filled: SFBubbleFill },
  { label: "Bubble Left",          outlineName: "SFBubbleLeft",                             filledName: "SFBubbleLeftFill",                            Outline: SFBubbleLeft,                             Filled: SFBubbleLeftFill },
  { label: "Envelope",             outlineName: "SFEnvelope",                               filledName: "SFEnvelopeFill",                              Outline: SFEnvelope,                               Filled: SFEnvelopeFill },
  { label: "Message",              outlineName: "SFMessage",                                filledName: "SFMessageFill",                               Outline: SFMessage,                                Filled: SFMessageFill },
  { label: "Microphone",           outlineName: "SFMicrophone",                             filledName: "SFMicrophoneFill",                            Outline: SFMicrophone,                             Filled: SFMicrophoneFill },
  { label: "Paperplane",           outlineName: "SFPaperplane",                             filledName: "SFPaperplaneFill",                            Outline: SFPaperplane,                             Filled: SFPaperplaneFill },
  { label: "Phone",                outlineName: "SFPhone",                                  filledName: "SFPhoneFill",                                 Outline: SFPhone,                                  Filled: SFPhoneFill },
  { label: "Video",                outlineName: "SFVideo",                                  filledName: "SFVideoFill",                                 Outline: SFVideo,                                  Filled: SFVideoFill },
  { label: "Waveform",             outlineName: "SFWaveform",                               filledName: "SFWaveformCircleFill",                        Outline: SFWaveform,                               Filled: SFWaveformCircleFill },
  { label: "Antenna",              outlineName: "SFAntennaRadiowavesLeftAndRight",          filledName: "SFAntennaRadiowavesLeftAndRightCircleFill",   Outline: SFAntennaRadiowavesLeftAndRight,          Filled: SFAntennaRadiowavesLeftAndRightCircleFill },
  // People & Gestures
  { label: "Person",               outlineName: "SFPerson",                                 filledName: "SFPersonFill",                                Outline: SFPerson,                                 Filled: SFPersonFill },
  { label: "Person 2",             outlineName: "SFPerson2",                                filledName: "SFPerson2Fill",                               Outline: SFPerson2,                                Filled: SFPerson2Fill },
  { label: "Person 3",             outlineName: "SFPerson3",                                filledName: "SFPerson3Fill",                               Outline: SFPerson3,                                Filled: SFPerson3Fill },
  { label: "Person Circle",        outlineName: "SFPersonCropCircle",                       filledName: "SFPersonCropCircleFill",                      Outline: SFPersonCropCircle,                       Filled: SFPersonCropCircleFill },
  { label: "Thumbs Up",            outlineName: "SFHandThumbsup",                           filledName: "SFHandThumbsupFill",                          Outline: SFHandThumbsup,                           Filled: SFHandThumbsupFill },
  { label: "Thumbs Down",          outlineName: "SFHandThumbsdown",                         filledName: "SFHandThumbsdownFill",                        Outline: SFHandThumbsdown,                         Filled: SFHandThumbsdownFill },
  { label: "Hand Wave",            outlineName: "SFHandWave",                               filledName: "SFHandWaveFill",                              Outline: SFHandWave,                               Filled: SFHandWaveFill },
  { label: "Hand Raised",          outlineName: "SFHandRaised",                             filledName: "SFHandRaisedFill",                            Outline: SFHandRaised,                             Filled: SFHandRaisedFill },
  { label: "Face",                 outlineName: "SFFaceDashed",                             filledName: "SFFaceDashedFill",                            Outline: SFFaceDashed,                             Filled: SFFaceDashedFill },
  // Media & Entertainment
  { label: "Play",                 outlineName: "SFPlay",                                   filledName: "SFPlayFill",                                  Outline: SFPlay,                                   Filled: SFPlayFill },
  { label: "Pause",                outlineName: "SFPause",                                  filledName: "SFPauseFill",                                 Outline: SFPause,                                  Filled: SFPauseFill },
  { label: "Repeat",               outlineName: "SFRepeat",                                 filledName: "SFRepeatCircleFill",                          Outline: SFRepeat,                                 Filled: SFRepeatCircleFill },
  { label: "Shuffle",              outlineName: "SFShuffle",                                filledName: "SFShuffleCircleFill",                         Outline: SFShuffle,                                Filled: SFShuffleCircleFill },
  { label: "Camera",               outlineName: "SFCamera",                                 filledName: "SFCameraFill",                                Outline: SFCamera,                                 Filled: SFCameraFill },
  { label: "Photo",                outlineName: "SFPhoto",                                  filledName: "SFPhotoFill",                                 Outline: SFPhoto,                                  Filled: SFPhotoFill },
  { label: "TV",                   outlineName: "SFTv",                                     filledName: "SFTvFill",                                    Outline: SFTv,                                     Filled: SFTvFill },
  { label: "Headphones",           outlineName: "SFHeadphones",                             filledName: "SFHeadphonesCircleFill",                      Outline: SFHeadphones,                             Filled: SFHeadphonesCircleFill },
  { label: "Gamecontroller",       outlineName: "SFGamecontroller",                         filledName: "SFGamecontrollerFill",                        Outline: SFGamecontroller,                         Filled: SFGamecontrollerFill },
  { label: "Metronome",            outlineName: "SFMetronome",                              filledName: "SFMetronomeFill",                             Outline: SFMetronome,                              Filled: SFMetronomeFill },
  { label: "Dice",                 outlineName: "SFDice",                                   filledName: "SFDiceFill",                                  Outline: SFDice,                                   Filled: SFDiceFill },
  // Files & Storage
  { label: "Archivebox",           outlineName: "SFArchivebox",                             filledName: "SFArchiveboxFill",                            Outline: SFArchivebox,                             Filled: SFArchiveboxFill },
  { label: "Book",                 outlineName: "SFBook",                                   filledName: "SFBookFill",                                  Outline: SFBook,                                   Filled: SFBookFill },
  { label: "Books",                outlineName: "SFBooksVertical",                          filledName: "SFBooksVerticalFill",                         Outline: SFBooksVertical,                          Filled: SFBooksVerticalFill },
  { label: "Clipboard",            outlineName: "SFClipboard",                              filledName: "SFClipboardFill",                             Outline: SFClipboard,                              Filled: SFClipboardFill },
  { label: "Document",             outlineName: "SFDocument",                               filledName: "SFDocumentFill",                              Outline: SFDocument,                               Filled: SFDocumentFill },
  { label: "Folder",               outlineName: "SFFolder",                                 filledName: "SFFolderFill",                                Outline: SFFolder,                                 Filled: SFFolderFill },
  { label: "Newspaper",            outlineName: "SFNewspaper",                              filledName: "SFNewspaperFill",                             Outline: SFNewspaper,                              Filled: SFNewspaperFill },
  { label: "Paperclip",            outlineName: "SFPaperclip",                              filledName: "SFPaperclipCircleFill",                       Outline: SFPaperclip,                              Filled: SFPaperclipCircleFill },
  { label: "Tray",                 outlineName: "SFTray",                                   filledName: "SFTrayFill",                                  Outline: SFTray,                                   Filled: SFTrayFill },
  // Commerce & Money
  { label: "Bag",                  outlineName: "SFBag",                                    filledName: "SFBagFill",                                   Outline: SFBag,                                    Filled: SFBagFill },
  { label: "Cart",                 outlineName: "SFCart",                                   filledName: "SFCartFill",                                  Outline: SFCart,                                   Filled: SFCartFill },
  { label: "Creditcard",           outlineName: "SFCreditcard",                             filledName: "SFCreditcardFill",                            Outline: SFCreditcard,                             Filled: SFCreditcardFill },
  { label: "Dollar",               outlineName: "SFDollarsign",                             filledName: "SFDollarsignCircleFill",                      Outline: SFDollarsign,                             Filled: SFDollarsignCircleFill },
  { label: "Euro",                 outlineName: "SFEurosign",                               filledName: "SFEurosignCircleFill",                        Outline: SFEurosign,                               Filled: SFEurosignCircleFill },
  { label: "Gift",                 outlineName: "SFGift",                                   filledName: "SFGiftFill",                                  Outline: SFGift,                                   Filled: SFGiftFill },
  { label: "Tag",                  outlineName: "SFTag",                                    filledName: "SFTagFill",                                   Outline: SFTag,                                    Filled: SFTagFill },
  // Navigation & Location
  { label: "Globe",                outlineName: "SFGlobe",                                  filledName: "SFGlobeFill",                                 Outline: SFGlobe,                                  Filled: SFGlobeFill },
  { label: "House",                outlineName: "SFHouse",                                  filledName: "SFHouseFill",                                 Outline: SFHouse,                                  Filled: SFHouseFill },
  { label: "Location",             outlineName: "SFLocation",                               filledName: "SFLocationFill",                              Outline: SFLocation,                               Filled: SFLocationFill },
  { label: "Map",                  outlineName: "SFMap",                                    filledName: "SFMapFill",                                   Outline: SFMap,                                    Filled: SFMapFill },
  { label: "Mappin",               outlineName: "SFMappin",                                 filledName: "SFMappinCircleFill",                          Outline: SFMappin,                                 Filled: SFMappinCircleFill },
  { label: "Airplane",             outlineName: "SFAirplane",                               filledName: "SFAirplaneCircleFill",                        Outline: SFAirplane,                               Filled: SFAirplaneCircleFill },
  { label: "Bicycle",              outlineName: "SFBicycle",                                filledName: "SFBicycleCircleFill",                         Outline: SFBicycle,                                Filled: SFBicycleCircleFill },
  { label: "Car",                  outlineName: "SFCar",                                    filledName: "SFCarCircleFill",                             Outline: SFCar,                                    Filled: SFCarCircleFill },
  // Security
  { label: "Key",                  outlineName: "SFKey",                                    filledName: "SFKeyFill",                                   Outline: SFKey,                                    Filled: SFKeyFill },
  { label: "Lock",                 outlineName: "SFLock",                                   filledName: "SFLockFill",                                  Outline: SFLock,                                   Filled: SFLockFill },
  { label: "Lock Open",            outlineName: "SFLockOpen",                               filledName: "SFLockOpenFill",                              Outline: SFLockOpen,                               Filled: SFLockOpenFill },
  { label: "Shield",               outlineName: "SFShield",                                 filledName: "SFShieldFill",                                Outline: SFShield,                                 Filled: SFShieldFill },
  // Analytics & Data
  { label: "Chart Bar",            outlineName: "SFChartBar",                               filledName: "SFChartBarFill",                              Outline: SFChartBar,                               Filled: SFChartBarFill },
  { label: "Chart Line Up",        outlineName: "SFChartLineUptrendXyaxis",                 filledName: "SFChartLineUptrendXyaxisCircleFill",          Outline: SFChartLineUptrendXyaxis,                 Filled: SFChartLineUptrendXyaxisCircleFill },
  { label: "Chart Pie",            outlineName: "SFChartPie",                               filledName: "SFChartPieFill",                              Outline: SFChartPie,                               Filled: SFChartPieFill },
  { label: "List",                 outlineName: "SFListBullet",                             filledName: "SFListBulletCircleFill",                      Outline: SFListBullet,                             Filled: SFListBulletCircleFill },
  // Actions
  { label: "Bookmark",             outlineName: "SFBookmark",                               filledName: "SFBookmarkFill",                              Outline: SFBookmark,                               Filled: SFBookmarkFill },
  { label: "Download",             outlineName: "SFSquareAndArrowDown",                     filledName: "SFSquareAndArrowDownFill",                    Outline: SFSquareAndArrowDown,                     Filled: SFSquareAndArrowDownFill },
  { label: "Eye",                  outlineName: "SFEye",                                    filledName: "SFEyeFill",                                   Outline: SFEye,                                    Filled: SFEyeFill },
  { label: "Heart",                outlineName: "SFHeart",                                  filledName: "SFHeartFill",                                 Outline: SFHeart,                                  Filled: SFHeartFill },
  { label: "Magnifyingglass",      outlineName: "SFMagnifyingglass",                        filledName: "SFMagnifyingglassCircleFill",                 Outline: SFMagnifyingglass,                        Filled: SFMagnifyingglassCircleFill },
  { label: "Pencil",               outlineName: "SFPencil",                                 filledName: "SFPencilCircleFill",                          Outline: SFPencil,                                 Filled: SFPencilCircleFill },
  { label: "Share",                outlineName: "SFSquareAndArrowUp",                       filledName: "SFSquareAndArrowUpFill",                      Outline: SFSquareAndArrowUp,                       Filled: SFSquareAndArrowUpFill },
  { label: "Scissors",             outlineName: "SFScissors",                               filledName: "SFScissorsCircleFill",                        Outline: SFScissors,                               Filled: SFScissorsCircleFill },
  { label: "Star",                 outlineName: "SFStar",                                   filledName: "SFStarFill",                                  Outline: SFStar,                                   Filled: SFStarFill },
  { label: "Trash",                outlineName: "SFTrash",                                  filledName: "SFTrashFill",                                 Outline: SFTrash,                                  Filled: SFTrashFill },
  // Tools & Creative
  { label: "Hammer",               outlineName: "SFHammer",                                 filledName: "SFHammerFill",                                Outline: SFHammer,                                 Filled: SFHammerFill },
  { label: "Paintbrush",           outlineName: "SFPaintbrush",                             filledName: "SFPaintbrushFill",                            Outline: SFPaintbrush,                             Filled: SFPaintbrushFill },
  { label: "Paintpalette",         outlineName: "SFPaintpalette",                           filledName: "SFPaintpaletteFill",                          Outline: SFPaintpalette,                           Filled: SFPaintpaletteFill },
  // System & UI
  { label: "Alarm",                outlineName: "SFAlarm",                                  filledName: "SFAlarmFill",                                 Outline: SFAlarm,                                  Filled: SFAlarmFill },
  { label: "At",                   outlineName: "SFAt",                                     filledName: "SFAtCircleFill",                              Outline: SFAt,                                     Filled: SFAtCircleFill },
  { label: "Bolt",                 outlineName: "SFBolt",                                   filledName: "SFBoltFill",                                  Outline: SFBolt,                                   Filled: SFBoltFill },
  { label: "Calendar",             outlineName: "SFCalendar",                               filledName: "SFCalendarCircleFill",                        Outline: SFCalendar,                               Filled: SFCalendarCircleFill },
  { label: "Checkmark",            outlineName: "SFCheckmark",                              filledName: "SFCheckmarkCircleFill",                       Outline: SFCheckmark,                              Filled: SFCheckmarkCircleFill },
  { label: "Checkmark Seal",       outlineName: "SFCheckmarkSeal",                          filledName: "SFCheckmarkSealFill",                         Outline: SFCheckmarkSeal,                          Filled: SFCheckmarkSealFill },
  { label: "Clock",                outlineName: "SFClock",                                  filledName: "SFClockFill",                                 Outline: SFClock,                                  Filled: SFClockFill },
  { label: "CPU",                  outlineName: "SFCpu",                                    filledName: "SFCpuFill",                                   Outline: SFCpu,                                    Filled: SFCpuFill },
  { label: "Diamond",              outlineName: "SFDiamond",                                filledName: "SFDiamondFill",                               Outline: SFDiamond,                                Filled: SFDiamondFill },
  { label: "Ellipsis",             outlineName: "SFEllipsis",                               filledName: "SFEllipsisCircleFill",                        Outline: SFEllipsis,                               Filled: SFEllipsisCircleFill },
  { label: "Exclamationmark",      outlineName: "SFExclamationmarkCircle",                  filledName: "SFExclamationmarkCircleFill",                 Outline: SFExclamationmarkCircle,                  Filled: SFExclamationmarkCircleFill },
  { label: "Flag",                 outlineName: "SFFlag",                                   filledName: "SFFlagFill",                                  Outline: SFFlag,                                   Filled: SFFlagFill },
  { label: "Gear",                 outlineName: "SFGear",                                   filledName: "SFGearshapeFill",                             Outline: SFGear,                                   Filled: SFGearshapeFill },
  { label: "Hourglass",            outlineName: "SFHourglass",                              filledName: "SFHourglassCircleFill",                       Outline: SFHourglass,                              Filled: SFHourglassCircleFill },
  { label: "Info",                 outlineName: "SFInfoCircle",                             filledName: "SFInfoCircleFill",                            Outline: SFInfoCircle,                             Filled: SFInfoCircleFill },
  { label: "iPhone",               outlineName: "SFIphone",                                 filledName: "SFIphoneCircleFill",                          Outline: SFIphone,                                 Filled: SFIphoneCircleFill },
  { label: "Keyboard",             outlineName: "SFKeyboard",                               filledName: "SFKeyboardFill",                              Outline: SFKeyboard,                               Filled: SFKeyboardFill },
  { label: "Link",                 outlineName: "SFLink",                                   filledName: "SFLinkCircleFill",                            Outline: SFLink,                                   Filled: SFLinkCircleFill },
  { label: "Minus",                outlineName: "SFMinus",                                  filledName: "SFMinusCircleFill",                           Outline: SFMinus,                                  Filled: SFMinusCircleFill },
  { label: "Plus",                 outlineName: "SFPlus",                                   filledName: "SFPlusCircleFill",                            Outline: SFPlus,                                   Filled: SFPlusCircleFill },
  { label: "Power",                outlineName: "SFPower",                                  filledName: "SFPowerCircleFill",                           Outline: SFPower,                                  Filled: SFPowerCircleFill },
  { label: "Questionmark",         outlineName: "SFQuestionmarkCircle",                     filledName: "SFQuestionmarkCircleFill",                    Outline: SFQuestionmarkCircle,                     Filled: SFQuestionmarkCircleFill },
  { label: "Timer",                outlineName: "SFTimer",                                  filledName: "SFTimerCircleFill",                           Outline: SFTimer,                                  Filled: SFTimerCircleFill },
  { label: "Xmark",                outlineName: "SFXmark",                                  filledName: "SFXmarkCircleFill",                           Outline: SFXmark,                                  Filled: SFXmarkCircleFill },
  // Nature & Weather
  { label: "Cloud",                outlineName: "SFCloud",                                  filledName: "SFCloudFill",                                 Outline: SFCloud,                                  Filled: SFCloudFill },
  { label: "Drop",                 outlineName: "SFDrop",                                   filledName: "SFDropCircleFill",                            Outline: SFDrop,                                   Filled: SFDropCircleFill },
  { label: "Flame",                outlineName: "SFFlame",                                  filledName: "SFFlameCircleFill",                           Outline: SFFlame,                                  Filled: SFFlameCircleFill },
  { label: "Leaf",                 outlineName: "SFLeaf",                                   filledName: "SFLeafCircleFill",                            Outline: SFLeaf,                                   Filled: SFLeafCircleFill },
  { label: "Moon",                 outlineName: "SFMoon",                                   filledName: "SFMoonFill",                                  Outline: SFMoon,                                   Filled: SFMoonFill },
  { label: "Snowflake",            outlineName: "SFSnowflake",                              filledName: "SFSnowflakeCircleFill",                       Outline: SFSnowflake,                              Filled: SFSnowflakeCircleFill },
  { label: "Sun",                  outlineName: "SFSunMax",                                 filledName: "SFSunMaxFill",                                Outline: SFSunMax,                                 Filled: SFSunMaxFill },
  // Health & Medical
  { label: "Cross",                outlineName: "SFCross",                                  filledName: "SFCrossFill",                                 Outline: SFCross,                                  Filled: SFCrossFill },
  { label: "Facemask",             outlineName: "SFFacemask",                               filledName: "SFFacemaskFill",                              Outline: SFFacemask,                               Filled: SFFacemaskFill },
  { label: "Stethoscope",          outlineName: "SFStethoscope",                            filledName: "SFStethoscopeCircleFill",                     Outline: SFStethoscope,                            Filled: SFStethoscopeCircleFill },
  // Places & Achievements
  { label: "Building",             outlineName: "SFBuilding2",                              filledName: "SFBuilding2Fill",                             Outline: SFBuilding2,                              Filled: SFBuilding2Fill },
  { label: "Building Columns",     outlineName: "SFBuildingColumns",                        filledName: "SFBuildingColumnsFill",                       Outline: SFBuildingColumns,                        Filled: SFBuildingColumnsFill },
  { label: "Bed",                  outlineName: "SFBedDouble",                              filledName: "SFBedDoubleFill",                             Outline: SFBedDouble,                              Filled: SFBedDoubleFill },
  { label: "Briefcase",            outlineName: "SFBriefcase",                              filledName: "SFBriefcaseFill",                             Outline: SFBriefcase,                              Filled: SFBriefcaseFill },
  { label: "Crown",                outlineName: "SFCrown",                                  filledName: "SFCrownFill",                                 Outline: SFCrown,                                  Filled: SFCrownFill },
  { label: "Cup & Saucer",         outlineName: "SFCupAndSaucer",                           filledName: "SFCupAndSaucerFill",                          Outline: SFCupAndSaucer,                           Filled: SFCupAndSaucerFill },
  { label: "Trophy",               outlineName: "SFTrophy",                                 filledName: "SFTrophyFill",                                Outline: SFTrophy,                                 Filled: SFTrophyFill },
  // Connectivity
  { label: "Wifi",                 outlineName: "SFWifi",                                   filledName: "SFWifiCircleFill",                            Outline: SFWifi,                                   Filled: SFWifiCircleFill },
  // Arrows (new)
  { label: "Arrow Up Down",        outlineName: "SFArrowUpArrowDown",                       filledName: "SFArrowUpArrowDownCircleFill",                Outline: SFArrowUpArrowDown,                       Filled: SFArrowUpArrowDownCircleFill },
  { label: "Arrow Left Right",     outlineName: "SFArrowLeftArrowRight",                    filledName: "SFArrowLeftArrowRightCircleFill",             Outline: SFArrowLeftArrowRight,                    Filled: SFArrowLeftArrowRightCircleFill },
  { label: "Arrow Vertical",       outlineName: "SFArrowUpAndDown",                         filledName: "SFArrowUpAndDownCircleFill",                  Outline: SFArrowUpAndDown,                         Filled: SFArrowUpAndDownCircleFill },
  // Communication (new)
  { label: "Bell Badge",           outlineName: "SFBellBadge",                              filledName: "SFBellBadgeFill",                             Outline: SFBellBadge,                              Filled: SFBellBadgeFill },
  { label: "Bell Slash",           outlineName: "SFBellSlash",                              filledName: "SFBellSlashFill",                             Outline: SFBellSlash,                              Filled: SFBellSlashFill },
  { label: "Envelope Badge",       outlineName: "SFEnvelopeBadge",                          filledName: "SFEnvelopeBadgeFill",                         Outline: SFEnvelopeBadge,                          Filled: SFEnvelopeBadgeFill },
  { label: "Envelope Open",        outlineName: "SFEnvelopeOpen",                           filledName: "SFEnvelopeOpenFill",                          Outline: SFEnvelopeOpen,                           Filled: SFEnvelopeOpenFill },
  // Audio & Media (new)
  { label: "Speaker",              outlineName: "SFSpeaker",                                filledName: "SFSpeakerFill",                               Outline: SFSpeaker,                                Filled: SFSpeakerFill },
  { label: "Speaker Wave",         outlineName: "SFSpeakerWave3",                           filledName: "SFSpeakerWave3Fill",                          Outline: SFSpeakerWave3,                           Filled: SFSpeakerWave3Fill },
  { label: "Speaker Slash",        outlineName: "SFSpeakerSlash",                           filledName: "SFSpeakerSlashFill",                          Outline: SFSpeakerSlash,                           Filled: SFSpeakerSlashFill },
  { label: "Speaker Circle",       outlineName: "SFSpeakerCircle",                          filledName: "SFSpeakerCircleFill",                         Outline: SFSpeakerCircle,                          Filled: SFSpeakerCircleFill },
  { label: "Record",               outlineName: "SFRecordCircle",                           filledName: "SFRecordCircleFill",                          Outline: SFRecordCircle,                           Filled: SFRecordCircleFill },
  { label: "Stop",                 outlineName: "SFStopCircle",                             filledName: "SFStopCircleFill",                            Outline: SFStopCircle,                             Filled: SFStopCircleFill },
  { label: "Airplay Video",        outlineName: "SFAirplayVideo",                           filledName: "SFAirplayVideoCircleFill",                    Outline: SFAirplayVideo,                           Filled: SFAirplayVideoCircleFill },
  { label: "Airplay Audio",        outlineName: "SFAirplayAudio",                           filledName: "SFAirplayAudioCircleFill",                    Outline: SFAirplayAudio,                           Filled: SFAirplayAudioCircleFill },
  // Actions (new)
  { label: "Eye Slash",            outlineName: "SFEyeSlash",                               filledName: "SFEyeSlashFill",                              Outline: SFEyeSlash,                               Filled: SFEyeSlashFill },
  { label: "Pin",                  outlineName: "SFPin",                                    filledName: "SFPinFill",                                   Outline: SFPin,                                    Filled: SFPinFill },
  { label: "Pin Circle",           outlineName: "SFPinCircle",                              filledName: "SFPinCircleFill",                             Outline: SFPinCircle,                              Filled: SFPinCircleFill },
  { label: "Location Circle",      outlineName: "SFLocationCircle",                         filledName: "SFLocationCircleFill",                        Outline: SFLocationCircle,                         Filled: SFLocationCircleFill },
  { label: "Location Slash",       outlineName: "SFLocationSlash",                          filledName: "SFLocationSlashFill",                         Outline: SFLocationSlash,                          Filled: SFLocationSlashFill },
  // Light & Home (new)
  { label: "Lightbulb",            outlineName: "SFLightbulb",                              filledName: "SFLightbulbFill",                             Outline: SFLightbulb,                              Filled: SFLightbulbFill },
  { label: "Lightbulb Circle",     outlineName: "SFLightbulbCircle",                        filledName: "SFLightbulbCircleFill",                       Outline: SFLightbulbCircle,                        Filled: SFLightbulbCircleFill },
  { label: "Lightbulb Max",        outlineName: "SFLightbulbMax",                           filledName: "SFLightbulbMaxFill",                          Outline: SFLightbulbMax,                           Filled: SFLightbulbMaxFill },
  { label: "Fireplace",            outlineName: "SFFireplace",                              filledName: "SFFireplaceFill",                             Outline: SFFireplace,                              Filled: SFFireplaceFill },
  // Devices (new)
  { label: "Printer",              outlineName: "SFPrinter",                                filledName: "SFPrinterFill",                               Outline: SFPrinter,                                Filled: SFPrinterFill },
  { label: "Scanner",              outlineName: "SFScanner",                                filledName: "SFScannerFill",                               Outline: SFScanner,                                Filled: SFScannerFill },
  { label: "Mac Mini",             outlineName: "SFMacmini",                                filledName: "SFMacminiFill",                               Outline: SFMacmini,                                Filled: SFMacminiFill },
  // System & UI (new)
  { label: "Number",               outlineName: "SFNumber",                                 filledName: "SFNumberCircleFill",                          Outline: SFNumber,                                 Filled: SFNumberCircleFill },
  { label: "Tablecells",           outlineName: "SFTablecells",                             filledName: "SFTablecellsFill",                            Outline: SFTablecells,                             Filled: SFTablecellsFill },
  { label: "Grid 3×3",             outlineName: "SFSquareGrid3x3",                          filledName: "SFSquareGrid3x3Fill",                         Outline: SFSquareGrid3x3,                          Filled: SFSquareGrid3x3Fill },
  { label: "Grid 2×2",             outlineName: "SFSquareGrid2x2",                          filledName: "SFSquareGrid2x2Fill",                         Outline: SFSquareGrid2x2,                          Filled: SFSquareGrid2x2Fill },
  // Sport & Fitness (new)
  { label: "Basketball",           outlineName: "SFBasketball",                             filledName: "SFBasketballFill",                            Outline: SFBasketball,                             Filled: SFBasketballFill },
  { label: "Baseball",             outlineName: "SFBaseball",                               filledName: "SFBaseballFill",                              Outline: SFBaseball,                               Filled: SFBaseballFill },
  { label: "Dumbbell",             outlineName: "SFDumbbell",                               filledName: "SFDumbbellFill",                              Outline: SFDumbbell,                               Filled: SFDumbbellFill },
  { label: "Volleyball",           outlineName: "SFVolleyball",                             filledName: "SFVolleyballFill",                            Outline: SFVolleyball,                             Filled: SFVolleyballFill },
  { label: "Hockey Puck",          outlineName: "SFHockeyPuck",                             filledName: "SFHockeyPuckFill",                            Outline: SFHockeyPuck,                             Filled: SFHockeyPuckFill },
  { label: "Figure Run",           outlineName: "SFFigureRun",                              filledName: "SFFigureRunCircleFill",                       Outline: SFFigureRun,                              Filled: SFFigureRunCircleFill },
  { label: "Figure Walk",          outlineName: "SFFigureWalk",                             filledName: "SFFigureWalkCircleFill",                      Outline: SFFigureWalk,                             Filled: SFFigureWalkCircleFill },
  { label: "Figure Yoga",          outlineName: "SFFigureYoga",                             filledName: "SFFigureYogaCircleFill",                      Outline: SFFigureYoga,                             Filled: SFFigureYogaCircleFill },
  { label: "Figure Dance",         outlineName: "SFFigureDance",                            filledName: "SFFigureDanceCircleFill",                     Outline: SFFigureDance,                            Filled: SFFigureDanceCircleFill },
  { label: "Figure Hiking",        outlineName: "SFFigureHiking",                           filledName: "SFFigureHikingCircleFill",                    Outline: SFFigureHiking,                           Filled: SFFigureHikingCircleFill },
  // People (new)
  { label: "Person Badge Key",     outlineName: "SFPersonBadgeKey",                         filledName: "SFPersonBadgeKeyFill",                        Outline: SFPersonBadgeKey,                         Filled: SFPersonBadgeKeyFill },
  // Places (new)
  { label: "Tent",                 outlineName: "SFTent",                                   filledName: "SFTentFill",                                  Outline: SFTent,                                   Filled: SFTentFill },
  { label: "Bathtub",              outlineName: "SFBathtub",                                filledName: "SFBathtubFill",                               Outline: SFBathtub,                                Filled: SFBathtubFill },
  { label: "Signpost Right",       outlineName: "SFSignpostRight",                          filledName: "SFSignpostRightFill",                         Outline: SFSignpostRight,                          Filled: SFSignpostRightFill },
  // Shapes (new)
  { label: "Triangle",             outlineName: "SFTriangle",                               filledName: "SFTriangleFill",                              Outline: SFTriangle,                               Filled: SFTriangleFill },
  { label: "Hexagon",              outlineName: "SFHexagon",                                filledName: "SFHexagonFill",                               Outline: SFHexagon,                                Filled: SFHexagonFill },
  { label: "Stopwatch",            outlineName: "SFStopwatch",                              filledName: "SFStopwatchFill",                             Outline: SFStopwatch,                              Filled: SFStopwatchFill },
  // Animals
  { label: "Ant",                  outlineName: "SFAnt",                                    filledName: "SFAntFill",                                   Outline: SFAnt,                                    Filled: SFAntFill },
  { label: "Cat",                  outlineName: "SFCat",                                    filledName: "SFCatFill",                                   Outline: SFCat,                                    Filled: SFCatFill },
  { label: "Dog",                  outlineName: "SFDog",                                    filledName: "SFDogFill",                                   Outline: SFDog,                                    Filled: SFDogFill },
  { label: "Fish",                 outlineName: "SFFish",                                   filledName: "SFFishFill",                                  Outline: SFFish,                                   Filled: SFFishFill },
  { label: "Tortoise",             outlineName: "SFTortoise",                               filledName: "SFTortoiseFill",                              Outline: SFTortoise,                               Filled: SFTortoiseFill },
  // Clothing & Fashion
  { label: "Cap",                  outlineName: "SFHatCap",                                 filledName: "SFHatCapFill",                                Outline: SFHatCap,                                 Filled: SFHatCapFill },
  { label: "Hat",                  outlineName: "SFHatWidebrim",                            filledName: "SFHatWidebrimFill",                           Outline: SFHatWidebrim,                            Filled: SFHatWidebrimFill },
  { label: "Shoe",                 outlineName: "SFShoe",                                   filledName: "SFShoeFill",                                  Outline: SFShoe,                                   Filled: SFShoeFill },
  { label: "T-Shirt",              outlineName: "SFTshirt",                                 filledName: "SFTshirtFill",                                Outline: SFTshirt,                                 Filled: SFTshirtFill },
  // Food & Drink
  { label: "Microwave",            outlineName: "SFMicrowave",                              filledName: "SFMicrowaveFill",                             Outline: SFMicrowave,                              Filled: SFMicrowaveFill },
  { label: "Mug",                  outlineName: "SFMug",                                    filledName: "SFMugFill",                                   Outline: SFMug,                                    Filled: SFMugFill },
  // Sports
  { label: "Am. Football",         outlineName: "SFAmericanFootball",                       filledName: "SFAmericanFootballFill",                      Outline: SFAmericanFootball,                       Filled: SFAmericanFootballFill },
  { label: "Backpack",             outlineName: "SFBackpack",                               filledName: "SFBackpackFill",                              Outline: SFBackpack,                               Filled: SFBackpackFill },
  { label: "Binoculars",           outlineName: "SFBinoculars",                             filledName: "SFBinocularsFill",                            Outline: SFBinoculars,                             Filled: SFBinocularsFill },
  { label: "Medal",                outlineName: "SFMedal",                                  filledName: "SFMedalFill",                                 Outline: SFMedal,                                  Filled: SFMedalFill },
  { label: "Medal Star",           outlineName: "SFMedalStar",                              filledName: "SFMedalStarFill",                             Outline: SFMedalStar,                              Filled: SFMedalStarFill },
  // Nature
  { label: "Beach",                outlineName: "SFBeachUmbrella",                          filledName: "SFBeachUmbrellaFill",                         Outline: SFBeachUmbrella,                          Filled: SFBeachUmbrellaFill },
  { label: "Sprinkler",            outlineName: "SFSprinkler",                              filledName: "SFSprinklerFill",                             Outline: SFSprinkler,                              Filled: SFSprinklerFill },
  { label: "Tree",                 outlineName: "SFTree",                                   filledName: "SFTreeFill",                                  Outline: SFTree,                                   Filled: SFTreeFill },
  { label: "Umbrella",             outlineName: "SFUmbrella",                               filledName: "SFUmbrellaFill",                              Outline: SFUmbrella,                               Filled: SFUmbrellaFill },
  // Travel & Transport
  { label: "Ferry",                outlineName: "SFFerry",                                  filledName: "SFFerryFill",                                 Outline: SFFerry,                                  Filled: SFFerryFill },
  { label: "Plane Ticket",         outlineName: "SFAirplaneTicket",                         filledName: "SFAirplaneTicketFill",                        Outline: SFAirplaneTicket,                         Filled: SFAirplaneTicketFill },
  { label: "Rolling Suitcase",     outlineName: "SFSuitcaseRolling",                        filledName: "SFSuitcaseRollingFill",                       Outline: SFSuitcaseRolling,                        Filled: SFSuitcaseRollingFill },
  { label: "Suitcase",             outlineName: "SFSuitcase",                               filledName: "SFSuitcaseFill",                              Outline: SFSuitcase,                               Filled: SFSuitcaseFill },
  { label: "Tram",                 outlineName: "SFTram",                                   filledName: "SFTramFill",                                  Outline: SFTram,                                   Filled: SFTramFill },
  // Entertainment & Media
  { label: "Balloon",              outlineName: "SFBalloon",                                filledName: "SFBalloonFill",                               Outline: SFBalloon,                                Filled: SFBalloonFill },
  { label: "Film",                 outlineName: "SFFilm",                                   filledName: "SFFilmFill",                                  Outline: SFFilm,                                   Filled: SFFilmFill },
  { label: "Guitars",              outlineName: "SFGuitars",                                filledName: "SFGuitarsFill",                               Outline: SFGuitars,                                Filled: SFGuitarsFill },
  { label: "Puzzle",               outlineName: "SFPuzzlepiece",                            filledName: "SFPuzzlepieceFill",                           Outline: SFPuzzlepiece,                            Filled: SFPuzzlepieceFill },
  { label: "Teddybear",            outlineName: "SFTeddybear",                              filledName: "SFTeddybearFill",                             Outline: SFTeddybear,                              Filled: SFTeddybearFill },
  // Health & Medical
  { label: "Accessibility",        outlineName: "SFAccessibility",                          filledName: "SFAccessibilityFill",                         Outline: SFAccessibility,                          Filled: SFAccessibilityFill },
  { label: "Ear",                  outlineName: "SFEar",                                    filledName: "SFEarFill",                                   Outline: SFEar,                                    Filled: SFEarFill },
  { label: "Pill",                 outlineName: "SFPill",                                   filledName: "SFPillFill",                                  Outline: SFPill,                                   Filled: SFPillFill },
  { label: "Syringe",              outlineName: "SFSyringe",                                filledName: "SFSyringeFill",                               Outline: SFSyringe,                                Filled: SFSyringeFill },
  // Home & Objects
  { label: "Chair",                outlineName: "SFChair",                                  filledName: "SFChairFill",                                 Outline: SFChair,                                  Filled: SFChairFill },
  { label: "Shipping Box",         outlineName: "SFShippingbox",                            filledName: "SFShippingboxFill",                           Outline: SFShippingbox,                            Filled: SFShippingboxFill },
  { label: "Sofa",                 outlineName: "SFSofa",                                   filledName: "SFSofaFill",                                  Outline: SFSofa,                                   Filled: SFSofaFill },
  { label: "Swatch Palette",       outlineName: "SFSwatchpalette",                          filledName: "SFSwatchpaletteFill",                         Outline: SFSwatchpalette,                          Filled: SFSwatchpaletteFill },
  { label: "Wallet",               outlineName: "SFWalletPass",                             filledName: "SFWalletPassFill",                            Outline: SFWalletPass,                             Filled: SFWalletPassFill },
  // Commerce
  { label: "Banknote",             outlineName: "SFBanknote",                               filledName: "SFBanknoteFill",                              Outline: SFBanknote,                               Filled: SFBanknoteFill },
  { label: "Pill Box",             outlineName: "SFPills",                                  filledName: "SFPillsFill",                                 Outline: SFPills,                                  Filled: SFPillsFill },
  { label: "Ticket",               outlineName: "SFTicket",                                 filledName: "SFTicketFill",                                Outline: SFTicket,                                 Filled: SFTicketFill },
  // Technology & Devices
  { label: "Earbuds Case",         outlineName: "SFEarbudsCase",                            filledName: "SFEarbudsCaseFill",                           Outline: SFEarbudsCase,                            Filled: SFEarbudsCaseFill },
  { label: "Heart Circle",         outlineName: "SFHeartCircle",                            filledName: "SFHeartCircleFill",                           Outline: SFHeartCircle,                            Filled: SFHeartCircleFill },
  { label: "Lodge",                outlineName: "SFHouseLodge",                             filledName: "SFHouseLodgeFill",                            Outline: SFHouseLodge,                             Filled: SFHouseLodgeFill },
  { label: "Mouse",                outlineName: "SFComputermouse",                          filledName: "SFComputermouseFill",                         Outline: SFComputermouse,                          Filled: SFComputermouseFill },
  // Misc
  { label: "Film Stack",           outlineName: "SFFilmStack",                              filledName: "SFFilmStackFill",                             Outline: SFFilmStack,                              Filled: SFFilmStackFill },
  { label: "Suitcase Cart",        outlineName: "SFSuitcaseCart",                           filledName: "SFSuitcaseCartFill",                          Outline: SFSuitcaseCart,                           Filled: SFSuitcaseCartFill },
];

export const BUTTON_ICON_MAP: Record<string, IconComponent> = Object.fromEntries(
  BUTTON_ICON_LIST.flatMap((e) => [
    [e.outlineName, e.Outline],
    [e.filledName, e.Filled],
  ]),
);
